---
title: "Graficos Clase 2"
author: "Yanina"
date: "11/3/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
```

## Elementos gramaticales esenciales


```{r}
ggplot(data = gapminder, 
       mapping = aes(x = gdpPercap, 
            y = lifeExp, 
           color = continent, 
           size = pop)) +
  geom_point()
```


```{r}

library(gapminder)
ggplot(gapminder, 
        aes(gdpPercap, 
            lifeExp)) + geom_point()

```

## Visualizar cantidades

```{r}
# Datos de Box Office Mojo para Dic. 22-24, 2017
boxoffice <- tibble(
  rank = 1:5,
  title = c("Star Wars", "Jumanji", "Pitch Perfect 3", "Greatest Showman", "Ferdinand"),
  amount = c(71.57, 36.17, 19.93, 8.81, 7.32) # millones de USD
)

```

```{r grafico_barras_col}

ggplot(boxoffice, aes(title, amount)) +
  geom_col()  # "col" es por columnas

```
```{r grafico_barras_col_ejes_cambiados}

ggplot(boxoffice, aes(amount, title)) +
  geom_col() +
  geom_text(aes(label = amount))# "col" es por columnas

```

```{r grafico_barras_col_ejes_cambiados_reordenado}

ggplot(boxoffice, aes(fct_reorder(title, amount), amount)) +
  geom_col()

ggplot(boxoffice, aes(amount,fct_reorder(title, amount))) +
  geom_col()


```

```{r}
pinguinos <- datos::pinguinos
head(pinguinos)
```

Objetivo: visualizar el número de pinguinos por especie

```{r grafico_barras_bar}

ggplot(pinguinos, aes(y = especie)) + # Atención: no se define x 
  geom_bar()

ggplot(pinguinos, aes(sexo, fill = especie)) +
  geom_bar() +
  coord_flip()



```

```{r histograma}

ggplot(pinguinos, aes(masa_corporal_g)) +
  geom_histogram()

```

```{r}
ggplot(pinguinos, aes(masa_corporal_g)) +
  geom_histogram(binwidth = 50) +
  
ggplot(pinguinos, aes(masa_corporal_g)) +
  geom_histogram(binwidth = 100) +
  
ggplot(pinguinos, aes(masa_corporal_g)) +
  geom_histogram(binwidth = 500) +

ggplot(pinguinos, aes(masa_corporal_g)) +
  geom_histogram(binwidth = 1000) +
  
patchwork::plot_layout(ncol = 2)
```


```{r histograma_intervalo}

ggplot(pinguinos, aes(masa_corporal_g)) +
  geom_histogram(binwidth = 50)

```

```{r densidad}
ggplot(pinguinos, aes(masa_corporal_g)) +
  geom_histogram() +
  labs(title = "Histograma") +
  
ggplot(pinguinos, aes(masa_corporal_g)) +
  geom_density() +
  labs(title = "Densidad por nucleos") +
  
patchwork::plot_layout(ncol = 2)

```

```{r}
ggplot(pinguinos, aes(masa_corporal_g)) +
  geom_density() +
  geom_rug(aes(y = -Inf), position = position_jitter(width = 10), sides = "b", alpha = 0.8)
```

```{r}
ggplot(pinguinos, aes(masa_corporal_g)) +
  geom_density() +
  
ggplot(pinguinos, aes(masa_corporal_g)) +
  geom_density(bw = 50) +
  
ggplot(pinguinos, aes(masa_corporal_g)) +
  geom_density(bw = 500) +
  
ggplot(pinguinos, aes(masa_corporal_g)) +
  geom_density(kernel = "rectangular", bw = 100) +
  
patchwork::plot_layout(ncol = 2)
```


```{r boxplot}
ggplot(pinguinos, aes(masa_corporal_g)) +
  geom_boxplot()

```

```{r boxplot_x_especie}
ggplot(pinguinos, aes(x= especie, y= masa_corporal_g)) +
  geom_boxplot()
```


